name = "love-scheduler"
main = "src/index.ts"
compatibility_date = "2025-01-06"
workers_dev = false

routes = [
  { pattern = "love.linzhiqing.dev/*", zone_name = "linzhiqing.dev" }
]

[triggers]
# TEMP: every 5 minutes for testing
crons = ["*/2 * * * *"]
